# =================================================================================================
#     Input Data
# =================================================================================================

# Set the input data, using file paths relative to the main snakemake directory
data:

  # Input table that lists all samples with their units and fastq files.
  samples: "../grenepipe/data/samples.tsv"

  # Directory where the mapped reads are stored. All `bam` and `bai` files from there are used.
  mapped_samples: "../grenepipe/run-f-100k/dedup"

  reference:

    # Path to the reference genome, using the file ideally as it is provided by the GATK bundle.
    genome: "../grenepipe/data/genome.fa"
