# =================================================================================================
#     Tool Parameters
# =================================================================================================

params:

  # ----------------------------------------------------------------------
  #     plink
  # ----------------------------------------------------------------------

  plink:
    extra: ""
