include: "../rules/common.smk"

# =================================================================================================
#     Target
# =================================================================================================

rule all:
    input:
        "out/freq.frq"

localrules: all

# =================================================================================================
#     PLINK
# =================================================================================================

rule frequencies_plink:
    input:
        config["data"]["called_variants"]
    output:
        "out/freq.frq",
        "out/freq.frq.counts"
    params:
        out_prefix = "out/freq"
    log:
        "out/freq.log"
    conda:
        "env.yaml"
    shell:
        "plink --vcf {input} --freq        --allow-extra-chr --out {params.out_prefix} >  {log} 2>&1 ;"
        "plink --vcf {input} --freq counts --allow-extra-chr --out {params.out_prefix} >> {log} 2>&1"
