include: "../rules/common.smk"

# =================================================================================================
#     Target
# =================================================================================================

rule all:
    input:
        "out/varslid.pdf"

localrules: all

# =================================================================================================
#     PoPoolation
# =================================================================================================

# Unfortunately, PoPoolation needs uncompressed pileup files...
rule popoolation_pileup:
    input:
        ref=config["data"]["reference"]["genome"],

        # Get the bam and bai files for all samples.
        samples=get_all_bams(),
        indices=get_all_bais(),
    output:
        "out/all.pileup"
        # temp( "popoolation/all.pileup" )
    log:
        "out/pileup.log"
    conda:
        "../envs/popoolation.yaml"
    shell:
        "samtools mpileup -f {input.ref} {input.samples} > {output} 2> {log}"

rule popoolation:
    input:
        pileup="out/all.pileup"
    output:
        "out/varslid.pdf"
    log:
        "out/varslid.log"
    conda:
        "env.yaml"
    shell:
        "scripts/popoolation.sh {input.pileup} \"" + get_contig_list() + "\" {output} > {log} 2>&1"
