import os

include: "../rules/common.smk"

# =================================================================================================
#     Target
# =================================================================================================

bam_basenames = [ os.path.basename(bam) for bam in get_all_bams() ]

rule all:
    input:
        expand( "out/{bam_basenames}.freq", bam_basenames=bam_basenames )

localrules: all

# =================================================================================================
#     bamfreq
# =================================================================================================

rule bamfreq:
    input:
        get_all_bams()
    output:
        [ "out/" + os.path.basename(bam) + ".freq" for bam in get_all_bams() ]
    params:
        out_prefix = "out/",
        extra = config["params"]["bamfreq"]["extra"]
    log:
        "out/bamfreq.log"
    run:
        for bam in input:
            out_file = "{params.out_prefix}" + os.path.basename(bam) + ".freq"
            shell( "tools/bamfreq/freq {params.extra} " + bam + " > " + out_file + " 2> {log}" )
        # "bamfreq {input} > {output} 2> {log}"
