# =================================================================================================
#     Input Data
# =================================================================================================

data:

  # Sample vcf containing the variants of all samples to be processed.
  vcf:
    "example/example.vcf.gz"

  # Input table containing the samples in the vcf file, along with their respective populations.
  # Needs to be tab-separated, and contain at least a column "sample", listing the sample names
  # (which correspond to the column names in th vcf file), as well as a column "population",
  # which names the population that the sample belongs to.
  samples:
    "example/samples.tsv"

  # List of contigs/chromosomes to process. This could be loaded from a fai file that is generated
  # from the vcf in the future, but for now, we hard code for simplicity.
  # The entries here can either be a simple list of the chromosome names, or, if the vcf file does
  # not contain the chromosome lengths in its header, the entries here need to be a dict from
  # chromosome names to their length. For example, either
  # - "1"
  # or
  # 1: "1000000"
  # work here.
  chromosomes:
    1: "1000000"

  # Define an output directory.
  output_dir: "out"

# =================================================================================================
#     Tool Parameters
# =================================================================================================

params:

  # ----------------------------------------------------------------------
  #     smcpp general
  # ----------------------------------------------------------------------

  smcpp:
    num_distinguished_individuals: 8

  # ----------------------------------------------------------------------
  #     smcpp vcf2smc
  # ----------------------------------------------------------------------

  smcpp_vcf2smc:
    extra: ""

  # ----------------------------------------------------------------------
  #     smcpp estimate / cv
  # ----------------------------------------------------------------------

  smcpp_estimate_cv:
    mutation_rate: "7e-9" # Mutation rate for Arabidopsis thaliana
    extra: ""

  # ----------------------------------------------------------------------
  #     smcpp plot
  # ----------------------------------------------------------------------

  smcpp_plot:
    extra: ""

  # ----------------------------------------------------------------------
  #     smcpp vcf2smc joint
  # ----------------------------------------------------------------------

  smcpp_vcf2smc_joint:
    extra: ""
